//
// Created by serik1987 on 15.12.2019.
//

#ifndef IHNA_KOZHUHOV_IMAGE_ANALYSIS_COMPILE_OPTIONS_H
#define IHNA_KOZHUHOV_IMAGE_ANALYSIS_COMPILE_OPTIONS_H

#define _USE_MATH_DEFINES
#define _CRT_SECURE_NO_WARNINGS

// #define DEBUG_CHUNK_LIST_DISPLAY
// #define DEBUG_DELETE_CHECK

#endif //IHNA_KOZHUHOV_IMAGE_ANALYSIS_COMPILE_OPTIONS_H
