#!/usr/bin/env python3
#-*- coding: utf-8


import sys
import matplotlib
matplotlib.use("wxAgg")

from ihna.kozhukhov.imageanalysis.gui import main

if __name__ == "__main__":
	if len(sys.argv) == 1:
		working_folder = "."
	else:
		working_folder = sys.argv[1]
	sys.exit(main(working_folder))
