//
// Created by serik1987 on 19.12.2019.
//

#ifndef IHNA_KOZHUKHOV_IMAGE_ANALYSIS_CORE_H
#define IHNA_KOZHUKHOV_IMAGE_ANALYSIS_CORE_H

#define GLOBAL_IMAN_NAMESPACE qzrywnjgerbeamqrtzai

#endif //IHNA_KOZHUKHOV_IMAGE_ANALYSIS_CORE_H
